### ISSUE TITLE
Parent lookup feature

### ISSUE THREAD

**Issue by ubyndr** [INCATools/PandaSaurus#26]
Should we add a parent lookup just like synonym lookup? @dosumis

**Comment by dosumis** [comment]
This feels like a special case of enrichment to me.  Maybe 'parent_enrichment' method on AnndataEnricher.

**Comment by dosumis** [comment]
MVP is just immediate parent, but it would be good to be able to specify number of hops.

**Comment by ubyndr** [comment]
Addressed in #37
